spring:
  application:
    name: zuul-gateway

server:
  port: 5555

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: test-Service
    api-b:
      path: /api-b/**
      serviceId: feign-Consumer

eureka:
  port: 10086
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka