spring:
  application:
    name: testController

server:
  eureka:
    port: 10086

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.eureka.port}/eureka

